"""empty message

Revision ID: 02e7dc0c6529
Revises: 
Create Date: 2023-02-09 11:38:24.552146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e7dc0c6529'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula_quimica',
    sa.Column('formula', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('formula')
    )
    op.create_table('tipo_equipamento',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('turma',
    sa.Column('cod', sa.String(length=10), nullable=False),
    sa.Column('ano', sa.SmallInteger(), nullable=True),
    sa.Column('turno', sa.Enum('Matutino', 'Vespertino', 'Noturno'), nullable=True),
    sa.Column('curso', sa.Enum('Eletrônica', 'Comércio', 'Informática para internet'), nullable=True),
    sa.Column('qtd_alunos', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('cod')
    )
    op.create_table('usuario',
    sa.Column('matricula', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('senha', sa.String(length=64), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('Professor', 'Tutor'), nullable=False),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('aula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turma', sa.String(length=10), nullable=True),
    sa.Column('data_aula', sa.Date(), nullable=True),
    sa.Column('roteiro', sa.String(length=500), nullable=True),
    sa.Column('professor', sa.Integer(), nullable=True),
    sa.Column('planejada_efetivada', sa.Enum('Planejada', 'Efetivada'), nullable=True),
    sa.Column('deletada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['professor'], ['usuario.matricula'], ),
    sa.ForeignKeyConstraint(['turma'], ['turma.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localizacao', sa.String(length=100), nullable=False),
    sa.Column('qtd', sa.SmallInteger(), nullable=False),
    sa.Column('volume', sa.SmallInteger(), nullable=False),
    sa.Column('tamanho', sa.SmallInteger(), nullable=False),
    sa.Column('tipo_equipamento', sa.String(length=100), nullable=False),
    sa.Column('lugar', sa.String(length=100), nullable=False),
    sa.Column('danificado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_equipamento'], ['tipo_equipamento.nome'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reagente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estado_materia', sa.Enum('Sólido', 'Líquido', 'Gasoso'), nullable=False),
    sa.Column('densidade', sa.Numeric(), nullable=False),
    sa.Column('massa', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('formula_quimica', sa.String(length=30), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['formula_quimica'], ['formula_quimica.formula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solucao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.Column('aula', sa.Integer(), nullable=True),
    sa.Column('formula_quimica', sa.String(length=30), nullable=True),
    sa.Column('estado_materia', sa.Enum('Sólido', 'Líquido', 'Gasoso'), nullable=True),
    sa.Column('densidade', sa.Numeric(), nullable=True),
    sa.Column('massa', sa.Numeric(), nullable=True),
    sa.Column('concentracao', sa.Numeric(), nullable=True),
    sa.Column('deletado_planejado', sa.Enum('Deletado', 'Planejado'), nullable=True),
    sa.ForeignKeyConstraint(['aula'], ['aula.id'], ),
    sa.ForeignKeyConstraint(['formula_quimica'], ['formula_quimica.formula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solucao_usa_reagente',
    sa.Column('solucao', sa.Integer(), nullable=False),
    sa.Column('reagente', sa.Integer(), nullable=False),
    sa.Column('massa', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['reagente'], ['reagente.id'], ),
    sa.ForeignKeyConstraint(['solucao'], ['solucao.id'], ),
    sa.PrimaryKeyConstraint('solucao', 'reagente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solucao_usa_reagente')
    op.drop_table('solucao')
    op.drop_table('reagente')
    op.drop_table('equipamento')
    op.drop_table('aula')
    op.drop_table('usuario')
    op.drop_table('turma')
    op.drop_table('tipo_equipamento')
    op.drop_table('formula_quimica')
    # ### end Alembic commands ###
